# -*- coding: utf-8 -*-
"""
Generates js/data.js (window.DATA) from the source content in src/data/.
Run:  python build.py     (or: npm run build)

Inputs:
  src/data/q_<EXAM>.json   one file per exam (14 exams, 10 questions each)
  src/data/lesson_<sec>.html  one micro-lesson per section
Output:
  js/data.js               window.DATA = { meta, lessons, questions }

OVERRIDES below are the *verified corrections / notes* applied at build time
(blank-answer fills + the three official-key clarifications surfaced by audit).
"""
import json, os, glob

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(ROOT, "src", "data")
OUT  = os.path.join(ROOT, "js", "data.js")

SECTIONS = [
    ("fork",        "Fork Counting",        "ספירת fork"),
    ("processes",   "Processes & States",   "תהליכים ומצבים"),
    ("scheduling",  "Scheduling",           "תזמון"),
    ("disk",        "Disk & Storage",       "דיסק ואחסון"),
    ("memory",      "Memory & Paging",      "זיכרון ודפדוף"),
    ("replacement", "Page Replacement",     "החלפת דפים"),
    ("sync",        "Synchronization",      "סנכרון"),
    ("interrupts",  "Interrupts & Mode",    "פסיקות ומצב"),
    ("systems",     "Systems Concepts",     "מושגי מערכת"),
]
SECTION_IDS = [s[0] for s in SECTIONS]

# Verified corrections / notes applied at build time, keyed by (exam, q).
OVERRIDES = {
    ("2017B", 10): {"answer_he": "מחזיר 1- (שגיאה)", "answer_en": "returns -1 (error)"},
    ("2019A", 9):  {"answer_he": "2 תהליכים, שניהם רצים (R)", "answer_en": "2 processes, both running (R)"},
    ("2019A", 10): {"answer_he": "semget", "answer_en": "semget"},
    ("2019B", 8):  {"answer_he": "הדף שלא ייעשה בו שימוש לזמן הארוך ביותר", "answer_en": "page used furthest in future"},
    ("2019B", 9):  {"answer_he": "1", "answer_en": "1"},
    ("2019B", 10): {"answer_he": "shmctl (IPC_RMID)", "answer_en": "shmctl (IPC_RMID)"},
    ("2017A", 9):  {"answer_he": "00", "answer_en": '"00"'},
    ("2020B", 6):  {"answer_he": "3 (לפי המחוון); SJF נוקשה=4", "answer_en": "3 ms (key); strict SJF=4",
                    "note": "Course key computed SJF as preemptive (SRTF) -> 3. Pure non-preemptive SJF = 4 ms. Write the course's value."},
    ("2023B", 6):  {"answer_he": "הרעבה / Bounded waiting", "answer_en": "Bounded waiting (-> starvation)",
                    "note": "Official key: 'starvation/הרעבה'. The violated CONDITION is Bounded Waiting; starvation is its consequence. Both usually accepted."},
    ("2017A", 7):  {"note": "Official phrasing. Real reason: the MMU translates on every memory access — far faster than trapping to the OS each time."},
}

def load_questions():
    qs = []
    for fp in sorted(glob.glob(os.path.join(DATA, "q_*.json"))):
        exam = os.path.basename(fp)[2:-5]            # q_2017A.json -> 2017A
        arr = json.load(open(fp, encoding="utf-8"))
        for item in arr:
            item["exam"] = exam
            key = (exam, int(item.get("q", 0)))
            if OVERRIDES.get(key):
                item.update(OVERRIDES[key])
            item["id"] = f"{exam}-{item.get('q')}"
            if item["section"] not in SECTION_IDS:
                raise SystemExit(f"Bad section '{item['section']}' in {item['id']}")
            if not item.get("he") or not (item.get("answer_he") or item.get("answer_en")):
                raise SystemExit(f"Missing text/answer in {item['id']}")
            qs.append(item)
    return qs

def load_lessons():
    out = {}
    for sid, *_ in SECTIONS:
        fp = os.path.join(DATA, f"lesson_{sid}.html")
        out[sid] = open(fp, encoding="utf-8").read() if os.path.exists(fp) else "<p><em>Lesson pending.</em></p>"
    return out

def main():
    questions = load_questions()
    counts = {s: 0 for s in SECTION_IDS}
    for q in questions:
        counts[q["section"]] += 1
    data = {
        "meta": {
            "course": "HIT 61206 — Operating Systems",
            "examDate": "2026-07-01",
            "sections": [{"id": s[0], "title": s[1], "he": s[2], "n": counts[s[0]]} for s in SECTIONS],
        },
        "lessons": load_lessons(),
        "questions": questions,
    }
    payload = json.dumps(data, ensure_ascii=False, indent=0)
    header = ("/* AUTO-GENERATED by build.py — do not edit by hand.\n"
              "   Edit the source content in src/data/ and re-run: python build.py */\n")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header + "window.DATA = " + payload + ";\n")
    print(f"Wrote {OUT}")
    print(f"  {len(questions)} questions across {len(SECTIONS)} sections: {counts}")

if __name__ == "__main__":
    main()
